---
title: "Detection and recognition of traffic signs"
subtitle: 'CMT307 Group 12 - Supervisor: Dev Kant'
author: "C. Huang; G. Jia; H. Zhang; M. Esposito; M. Jepson; X. Zhu; Z. Tang; J. Mendoza"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document:
    toc: yes
  bookdown::pdf_document2:
    citation_package: natbib
    df_print: kable
    extra_dependencies:
      caption: labelfont={bf}
    fig_caption: yes
    highlight: haddock
    keep_tex: yes
    number_sections: yes
    toc: yes
biblio-style: apalike
email: studenta@cardiff.ac.uk
fontfamily: times
fontsize: 11pt
geometry: margin=1in
link-citations: yes
bibliography: refs.bib

abstract: The present document is a coursework report for the module CMT307 Applied Machine Learning, academic year 2021-2022. This document describes the deployment and implementation of a Convolutional Neural Network used for Computer Vision, with the scope of classifying a set of traffic signs pictures from the German Traffic Sign Recognition Benchmark (GTSRB).
---

<!-- set knitr options here -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- main body starts here -->

\pagebreak



# 1. Introduction {#intro}

Summary of the task and main goals/contributions/insights of the project.

The scope of this project is to develope a machine learning model capable of identify and classify traffic signs with the use of pictures, what is known in the industry as *Computer Vision.*

The data sources to train and test this model was obtained from the German Traffic Sign Recognition Benchmark (GTSRB)[^1]. Links to this datasets are provided in Appendix 1. The project will consist of several python scripts that will decode pictures into numpy arrays to build the initial dataset, analyze and manipulate these pictures to finally be fed into a *Convolutional Neuronal Network* (CNN from now on) whose performance and implementation will be discussed, alongside different strategies and alternatives to improve performance. The choice of this machine learning method, as well as the CNN architechture and other computer vision alternatives, will be discussed in the later sections of this report.


[^1]: https://sid.erda.dk/public/archives/daaeac0d7ce1152aea9b61d9f1e19370/published-archive.html




# 2. Literature review / Related work {#sec:literature}

Overview of the related work most connected to the methods and tasks of the projects. Explain the differences and the connection between works in the literature with respect to the employed method (e.g. advantages/disadvantages, ideas you exploited, etc.).
Tip: Google Scholar is a good resource to find relevant articles to any of the topics.




# 3. Description of the task/dataset

Description of the task and dataset, including relevant statistics of dataset splits.

The aforementioned dataset 



# 4. Methodology

Description of the machine learning methods used in the project.




# 5. Experimental setting

Description of the specific details of the evaluation (e.g. parameter tuning, usage of the development set).




# 6. Results

Final results of the experiments, including baselines and table/s with precision/recall/accuracy/f1, etc.




# 7. Analysis

Analysis of the results, error analysis (investigate the type of error the system makes, etc.).




# 8. Conclusion and future work

Summary of the main conclusions and takeaways from the experiments. Explain ways to investigate or improve the method in the future.















# Appendix 1
- This is the first appendix
- First appendix

\pagebreak




# Appendix 2
Second appendix without listing item

\pagebreak






# Citations 
See for example [@avendi01], [@chollet01] and [@geron01] .





